### PR TITLE
AB#312 Add Step log for Allure report for tasks in Sprint 3

### PR DESCRIPTION
**Pull request by tuanna0308**
Report:
image

Done:
- Add Step log for tasks in the previous Sprint (Sprint 3)

### CODE REVIEW

**Review by khiemkao — APPROVED** [review]
look good

**Review by LuanNguyenBao — COMMENTED** [review]
As discussed, we should remove arguments that contain a locator in @Step.

**Comment by tuanna0308** [comment]
@LuanNguyenBao please help me to review it again

**Review by khiemkao — APPROVED** [review]

**Review by LuanNguyenBao — APPROVED** [review]
It looks good to me.

**Pull request merged**
